language: node_js

node_js:
  - node

cache: yarn

script:
  - yarn ci

notifications:
  slack:
    rooms:
      secure: LvA3D4ZZyEifMtH/pGpjmiEYeEYxgOTvn0ydJDUX0oG68rynZm9V+i4oAxFg18b8YAsZX+YjiWXxwdZYVwdHK8w0GJTMGysIMRw0TY5hEKDPJqqo2/X6BpQXG7tR4OYXrGGFSTeKqDdmC8vECxpQYEL/F0pc/YLnp9MjxT46CJiFOKR7q58WLRh3lJQge0AQI21ylSAHX7cA7Bnw6zIK44c2JYdpIwX8WOBtLZ7YgyvvtY87KQ7mQmpBS5V/5Cmx0tKCKNSFQd0HUALNnDPr7bQJcSmiJeLCO1VGdAe8OpFsa88XUfh34ZIU/MOjpDDo5yhp+uMoQ5fegiG/OfCOVUubzyjl0QSXLuBsIkE0T17eo0eoTwJH92zG6JEThegft5dNeutsYQjy/ObCbHJSK3jmb0zNJPo8XjebiRPsYLjXrAIqJTkOJmV2ndyJiMPEz6PP1Qpc/rkLvGD3i1X8IwQNz4AB0LiuZOpRxYmypsAMxWkg/DRPihLZbbH/4+IiYyxY2OnXvjPOr6AZ2Y9pcgMKYoWSKAd36WLpcEhFLIeA5exw3kvZmqRerr2KkDUIovUO+Zxo8WjzZCV4CWzqiRGo7ZjS0/MR6bVnHSG66oYtCWBBtPYtsxNqqZ7oDWYlC8SBsrgqTjk/ShlYNX/uSyavwQVhu7B0W+i15pXEVCg=
    on_success: always
    on_failure: always
    on_error: always
    template:
      - 'Build %{result}: %{repository_slug}'
      - 'Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) on %{branch} by %{author} %{result} in %{duration}'
