language: node_js

node_js:
  - node

cache: yarn

script:
  - yarn ci

notifications:
  slack:
    rooms:
      secure: FyIcx7ZiN7ETq2q7WzBJB1cdFQxKWJaDSjAMvllykn1MBb5hQ1EQQuEekXOh27fuk05Jy/c6dKmOju8iwO6DqyWp6uyBVnr4uZGXD0QRX9Di7HQgfrTU2qFD9xYfL24bkESzwC7dBd6+90kVnqiMMSfBkVnoGb1ubPuGsogaJpJQjw6GIamIw67vpg1GyquGwX+rYkvB4eIzybFGXiO2XBvu1zxeF7nVF8muU1Jqi23DPAP37m1p15PtRRJdud5+zkPDq8Ug78EI1D5T6Rz/45gV14fiKZ/BpUeZECgpGT2bzg/l0O3NlrRF56MKIafi5eZoUOneoK2AiBvmSVsO4Q0pSqQOl4b0gs0h8lhr4Xkm1m/wL2qBBnvnDiyhr8hawAjhmYcoFmSO2x7YKPvtUv4qt4N0TJXW4P49hg2W0YPgGA//dOmChRkFEmRq4OW60UTRduJDUpAAn3jGC1b9iaEqcR9b3dpNudv7QZcsDPyvlLkjiMMmPt5m0uKleCEJ55IeTJsNSJ3425u3+6N3sg2edlFsrcieyC32+roWhkjNiBaDEDmNVFpw07aV9mS6H+otSVkpOClme6RDEnMnoaukFiZa4nRZAlZRf49XW2fAcIVInFDonCtC2/FxVn/j1Eor7kgeeIVh53J/DI9qRXiz2KVJjb5h7yc1PpMR5gk=
    on_success: always
    on_failure: always
