name: CI/CD

on: push

jobs:
  ci:
    name: Integration
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn install --ignore-scripts
      - run: yarn ci
